services:
  mqtt:
    build: .
    restart: unless-stopped
    ports:
      - "80:8080"
      - "7006:7006"
    environment:
      CERTBOT_DOMAIN: mqtt.example.de
      CERTBOT_EMAIL: admin@example.de
      GROWAT_SN: "AAAA,BBBB"
      GROBRO_USER: "grobro"
      GROBRO_PASS: "Growatt"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./mosquitto-data:/mosquitto/data
