persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
autosave_interval 300

log_dest stdout
connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S


listener 7006
allow_anonymous false
password_file /mosquitto/config/passwordfile

certfile /mosquitto/certs/server.pem
keyfile /mosquitto/certs/server.key
