persistence true
persistence_location /mosquitto/data/

log_dest stdout

listener 7006
allow_anonymous false
password_file /mosquitto/config/passwordfile

certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem
