[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

#
# Initialisierung
#
[program:init]
command=/bin/sh -c "/usr/local/bin/create-mosquitto-users.sh && /usr/local/bin/certbot-renew.sh"
user=root
priority=1
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

#
# MQTT Broker
#
[program:mosquitto]
command=mosquitto -c /etc/mosquitto/mosquitto.conf
user=mosquitto
priority=10
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

#
# Cron
#
[program:cron]
command=crond -f -l 2
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0
