[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
user=root

#
# Init
# 
[program:init-permissions]
command=/bin/sh -c "/usr/local/bin/init-permissions.sh"
user=root
priority=1
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

[program:create-mosquitto-users]
command=/bin/sh -c "/usr/local/bin/create-mosquitto-users.sh"
user=mosquitto
priority=2
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

[program:init-certbot-renew]
command=/bin/sh -c "/usr/local/bin/certbot-renew.sh"
user=certbot
priority=3
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

#
# MQTT Broker
#
[program:mosquitto]
command=/usr/local/bin/start-mosquitto.sh
user=mosquitto
priority=10
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

#
# Cron
#
[program:cron]
command=crond -f -l 0
user=root
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0
