[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

#
# Init
#
[program:init-mosquitto]
command=/bin/sh -c "/usr/local/bin/create-mosquitto-users.sh"
user=mosquitto
priority=1
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

[program:init-cerbot]
command=/bin/sh -c "/usr/local/bin/certbot-renew.sh"
user=certbot
priority=2
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

#
# MQTT Broker
#
[program:mosquitto]
command=/usr/local/bin/start-mosquitto.sh
user=mosquitto
priority=10
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0

#
# Cron
#
[program:cron]
command=crond -f -l 2
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes = 0
